env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
  tsconfigRootDir: './'
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  import/order:
    - error
    - groups:
        - ['builtin', 'external']
        - internal
        - ['parent', 'sibling']
        - index
      pathGroups:
        - pattern: 'react'
          group: 'external'
          position: 'before'
      newlines-between: 'always'
  lines-between-class-members:
    - error
    - always
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  import/resolver:
    typescript: {}
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
